<?php
/**
 * Copyright (c) 2016-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the license found in the
 * LICENSE file in the root directory of this source tree.
 */
namespace Facebook\InstantArticles\Transformer;

use Facebook\InstantArticles\Elements\InstantArticle;
use Facebook\Util\BaseHTMLTestCase;

class SimpleTransformerTest extends BaseHTMLTestCase
{
    public function testSelfTransformerContent()
    {
        $json_file = file_get_contents(__DIR__ . '/simple-rules.json');

        $instant_article = InstantArticle::create();
        $transformer = new Transformer();
        $transformer->loadRules($json_file);

        $html_file = file_get_contents(__DIR__ . '/simple.html');

        $transformer->transformString($instant_article, $html_file);
        $instant_article->addMetaProperty('op:generator:version', '1.0.0');
        $instant_article->addMetaProperty('op:generator:transformer:version', '1.0.0');
        $result = $instant_article->render('', true)."\n";
        $expected = file_get_contents(__DIR__ . '/simple-ia.html');

        //var_dump($result);
        // print_r($warnings);
        $this->assertEqualsHtml($expected, $result);
    }

    public function testDebugLog()
    {
        $expected = array(
            'Possible log levels: OFF, ERROR, INFO or DEBUG',
            '[INFO] Transformer initiated using encode [utf-8]',
            '[DEBUG] Will transform content [<html>'.
            '    <head>'.
            '        <script type="text/javascript" href="http://domain.com/javascript.js" />'.
            '    </head>'.
            '    <body>'.
            '        <div class="header">'.
            '            <h1>The article title</h1>'.
            '        </div>'.
            '        <p>Lorem <b>ipsum</b> dolor sit amet.</p>'.
            '        <div class="image">'.
            '            <img src="http://domain.com/image-body.png" alt="Photographer"/>'.
            '        </div>'.
            '    </body>'.
            '</html>'.
            ']',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\RelatedArticlesRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\FooterRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\SocialEmbedRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ParagraphRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\RelatedArticlesRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\FooterRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\SocialEmbedRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ParagraphRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [html]',
            '[DEBUG] MATCH -> Rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] applied to node [html]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\RelatedArticlesRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\FooterRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\SocialEmbedRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ParagraphRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\RelatedArticlesRule] not matched to node [head]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\FooterRule] not matched to node [head]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\SocialEmbedRule] not matched to node [head]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [head]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [head]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [head]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [head]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderRule] not matched to node [head]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ParagraphRule] not matched to node [head]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [head]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [head]',
            '[DEBUG] MATCH -> Rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] applied to node [head]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\RelatedArticlesRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\FooterRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\SocialEmbedRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ParagraphRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\RelatedArticlesRule] not matched to node [script]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\FooterRule] not matched to node [script]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\SocialEmbedRule] not matched to node [script]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [script]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [script]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [script]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [script]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderRule] not matched to node [script]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ParagraphRule] not matched to node [script]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [script]',
            '[DEBUG] MATCH -> Rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] applied to node [script]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\RelatedArticlesRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\FooterRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\SocialEmbedRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ParagraphRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\RelatedArticlesRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\FooterRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\SocialEmbedRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ParagraphRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\RelatedArticlesRule] not matched to node [body]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\FooterRule] not matched to node [body]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\SocialEmbedRule] not matched to node [body]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [body]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [body]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [body]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [body]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderRule] not matched to node [body]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ParagraphRule] not matched to node [body]',
            '[DEBUG] MATCH -> Rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] applied to node [body]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\RelatedArticlesRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\FooterRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\SocialEmbedRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ParagraphRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\RelatedArticlesRule] not matched to node [div]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\FooterRule] not matched to node [div]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\SocialEmbedRule] not matched to node [div]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [div]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [div]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [div]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [div]',
            '[DEBUG] MATCH -> Rule [Facebook\InstantArticles\Transformer\Rules\HeaderRule] applied to node [div]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\AuthorRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderSubTitleRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderTitleRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderImageRule] not matched to node [h1]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\AuthorRule] not matched to node [h1]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderSubTitleRule] not matched to node [h1]',
            '[DEBUG] MATCH -> Rule [Facebook\InstantArticles\Transformer\Rules\HeaderTitleRule] applied to node [h1]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\BoldRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ItalicRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] MATCH -> Rule [Facebook\InstantArticles\Transformer\Rules\TextNodeRule] applied to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\AuthorRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderSubTitleRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderTitleRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\RelatedArticlesRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\FooterRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\SocialEmbedRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ParagraphRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\RelatedArticlesRule] not matched to node [p]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\FooterRule] not matched to node [p]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\SocialEmbedRule] not matched to node [p]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [p]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [p]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [p]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [p]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderRule] not matched to node [p]',
            '[DEBUG] MATCH -> Rule [Facebook\InstantArticles\Transformer\Rules\ParagraphRule] applied to node [p]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\BoldRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ItalicRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] MATCH -> Rule [Facebook\InstantArticles\Transformer\Rules\TextNodeRule] applied to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [b]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [b]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [b]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [b]',
            '[DEBUG] MATCH -> Rule [Facebook\InstantArticles\Transformer\Rules\BoldRule] applied to node [b]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\BoldRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ItalicRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] MATCH -> Rule [Facebook\InstantArticles\Transformer\Rules\TextNodeRule] applied to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\BoldRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ItalicRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] MATCH -> Rule [Facebook\InstantArticles\Transformer\Rules\TextNodeRule] applied to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\RelatedArticlesRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\FooterRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\SocialEmbedRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ParagraphRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\RelatedArticlesRule] not matched to node [div]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\FooterRule] not matched to node [div]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\SocialEmbedRule] not matched to node [div]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [div]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [div]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [div]',
            '[DEBUG] MATCH -> Rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] applied to node [div]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\BoldRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ItalicRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] MATCH -> Rule [Facebook\InstantArticles\Transformer\Rules\TextNodeRule] applied to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\BoldRule] not matched to node [img]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ItalicRule] not matched to node [img]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [img]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [img]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [img]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [img]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\TextNodeRule] not matched to node [img]',
            '[ERROR] Content with no rules matching! Context[Facebook\InstantArticles\Elements\Caption] and Node [img]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\BoldRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ItalicRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] MATCH -> Rule [Facebook\InstantArticles\Transformer\Rules\TextNodeRule] applied to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\CaptionRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\CaptionRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] MATCH -> Rule [Facebook\InstantArticles\Transformer\Rules\CaptionRule] applied to node [img]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\CaptionRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\CaptionRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\RelatedArticlesRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\FooterRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\SocialEmbedRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ParagraphRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\RelatedArticlesRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\FooterRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\SocialEmbedRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ImageRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\HeaderRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\ParagraphRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]',
            '[DEBUG] no match -> rule [Facebook\InstantArticles\Transformer\Rules\PassThroughRule] not matched to node [#text]'
        );
        $json_file = file_get_contents(__DIR__ . '/simple-rules.json');

        $instant_article = InstantArticle::create();
        $transformer = new Transformer();
        $transformer->loadRules($json_file);

        $html_file = file_get_contents(__DIR__ . '/simple.html');

        $transformer->setLogLevel(Transformer::LOG_DEBUG);
        $transformer->transformString($instant_article, $html_file);
        $result = $transformer->getLogs();

        array_pop($result);

        $this->assertEqualsHtml($expected, $result);
    }
}
